In [1]:
import pandas as pd

In [2]:
filepath = r"C:\Users\HP\Desktop\Projects - Data Analysis\RSF\CKM_Dummy_EHR_Dataset.xlsx"
total_data = pd.ExcelFile(path_or_buffer= filepath)

sheet_dict = dict()
for sheetname in total_data.sheet_names:
    sheet_dict[sheetname] = total_data.parse(sheet_name= sheetname)

In [3]:
patient_data, encounter_data, vitals_data, lab_test_data, diagnosis_data, medications_data, history_data, procedures_data = sheet_dict.values()

In [4]:
df_patient_data = patient_data.drop(columns=[
    'insurance_category', 'cause_of_death'])
df_enctr_data = encounter_data.drop(columns=[
    'facility_code', 'facility_name', 'encounter_type', 'discharge_status'
    ])
df_vitals_data = vitals_data.drop(columns=[
    'height_unit', 'weight_unit', 'bmi_unit', 'waist_circumference_unit', 
    'source_facility_code'])
df_lab_test_data = lab_test_data.drop(columns=[
    'result_value_text', 'reference_low', 'reference_high', 'result_status', 
    'facility_code'])
df_diagnosis_data = diagnosis_data.drop(columns=[
    'diagnosis_type', 'diagnosis_source', 'active_status'])
df_medications_data = medications_data.drop(columns=[
    'medication_record_id', 'generic_name', 'medication_code', 'frequency', 
    'route', 'medication_status', 'order_date', 'start_date', 'end_date'])                                                
df_history_data = history_data.drop(columns=[
    'recorded_date', 'data_source'])
df_procedures_data = procedures_data.drop(columns=[
    'event_date', 'event_category', 'description', 'status', 'facility_code', 
    'result_unit'])

Pivot Tables

In [5]:
pivot_lab = pd.pivot_table(lab_test_data, values= 'result_value_numeric', 
                            index= ['patient_id', 'encounter_id', 'test_datetime'],
                            columns= 'test_name')
pivot_lab

test_name                                     ALT  Fasting Glucose  \
patient_id encounter_id test_datetime
PT000001   ENC00000002  2015-07-19 13:00:00   NaN            110.0
           ENC00000003  2015-10-28 08:00:00   NaN              NaN
           ENC00000004  2016-05-29 12:00:00   NaN             87.0
           ENC00000005  2017-08-19 09:00:00  20.0            110.0
           ENC00000006  2017-09-21 07:00:00   NaN              NaN
...                                           ...              ...
PT001200   ENC00028647  2019-07-09 08:00:00   7.0             78.0
           ENC00028648  2020-12-28 14:00:00   NaN             64.0
           ENC00028649  2021-01-24 09:00:00  28.0            128.0
           ENC00028650  2022-04-22 07:00:00   NaN            109.0
           ENC00028652  2023-10-20 09:00:00  29.0            102.0

test_name                                    HDL Cholesterol  HbA1c  \
patient_id encounter_id test_datetime
PT000001   ENC00000002  2015-07-19 13:00:00             43.0    NaN
           ENC00000003  2015-10-28 08:00:00             47.0    6.3
           ENC00000004  2016-05-29 12:00:00              NaN    4.9
           ENC00000005  2017-08-19 09:00:00             70.0    7.9
           ENC00000006  2017-09-21 07:00:00             38.0    NaN
...                                                      ...    ...
PT001200   ENC00028647  2019-07-09 08:00:00             49.0    6.7
           ENC00028648  2020-12-28 14:00:00              NaN    4.7
           ENC00028649  2021-01-24 09:00:00             43.0    NaN
           ENC00028650  2022-04-22 07:00:00             51.0    5.0
           ENC00028652  2023-10-20 09:00:00             55.0    4.8

test_name                                    Hemoglobin  LDL Cholesterol  \
patient_id encounter_id test_datetime
PT000001   ENC00000002  2015-07-19 13:00:00         NaN            108.0
           ENC00000003  2015-10-28 08:00:00        15.0              NaN
           ENC00000004  2016-05-29 12:00:00        14.9            115.0
           ENC00000005  2017-08-19 09:00:00        14.4              NaN
           ENC00000006  2017-09-21 07:00:00         NaN            104.0
...                                                 ...              ...
PT001200   ENC00028647  2019-07-09 08:00:00        11.8             53.0
           ENC00028648  2020-12-28 14:00:00        15.5            109.0
           ENC00028649  2021-01-24 09:00:00        15.7            101.0
           ENC00028650  2022-04-22 07:00:00         NaN             75.0
           ENC00028652  2023-10-20 09:00:00        12.9             78.0

test_name                                    Potassium  Serum Albumin  \
patient_id encounter_id test_datetime
PT000001   ENC00000002  2015-07-19 13:00:00        NaN            NaN
           ENC00000003  2015-10-28 08:00:00        NaN            NaN
           ENC00000004  2016-05-29 12:00:00        NaN            4.2
           ENC00000005  2017-08-19 09:00:00        4.4            NaN
           ENC00000006  2017-09-21 07:00:00        3.9            3.9
...                                                ...            ...
PT001200   ENC00028647  2019-07-09 08:00:00        NaN            3.9
           ENC00028648  2020-12-28 14:00:00        NaN            4.6
           ENC00028649  2021-01-24 09:00:00        4.4            NaN
           ENC00028650  2022-04-22 07:00:00        4.0            4.4
           ENC00028652  2023-10-20 09:00:00        3.7            3.9

test_name                                    Serum Creatinine  Sodium  \
patient_id encounter_id test_datetime
PT000001   ENC00000002  2015-07-19 13:00:00               NaN     NaN
           ENC00000003  2015-10-28 08:00:00               NaN     NaN
           ENC00000004  2016-05-29 12:00:00               NaN   136.0
           ENC00000005  2017-08-19 09:00:00              0.65   143.0
           ENC00000006  2017-09-21 07:00:00              0.74   140.0
...                                                       ...     ...
PT001200   ENC00028647  2019-07-09 08:00:00               NaN   141.0
           ENC00028648  2020-12-28 14:00:00               NaN     NaN
           ENC00028649  2021-01-24 09:00:00               NaN   145.0
           ENC00028650  2022-04-22 07:00:00              1.00     NaN
           ENC00028652  2023-10-20 09:00:00              0.75   144.0

test_name                                    Triglycerides  UACR  Uric Acid  \
patient_id encounter_id test_datetime
PT000001   ENC00000002  2015-07-19 13:00:00            NaN  16.6        NaN
           ENC00000003  2015-10-28 08:00:00            NaN   NaN        5.6
           ENC00000004  2016-05-29 12:00:00           63.0  26.2        5.0
           ENC00000005  2017-08-19 09:00:00           71.0   6.5        5.0
           ENC00000006  2017-09-21 07:00:00          137.0  15.7        4.9
...                                                    ...   ...        ...
PT001200   ENC00028647  2019-07-09 08:00:00          136.0   3.4        5.5
           ENC00028648  2020-12-28 14:00:00          109.0   9.7        4.0
           ENC00028649  2021-01-24 09:00:00            NaN   9.0        4.5
           ENC00028650  2022-04-22 07:00:00            NaN   8.5        2.6
           ENC00028652  2023-10-20 09:00:00          111.0   8.0        6.0

test_name                                     eGFR
patient_id encounter_id test_datetime
PT000001   ENC00000002  2015-07-19 13:00:00    NaN
           ENC00000003  2015-10-28 08:00:00  103.5
           ENC00000004  2016-05-29 12:00:00   83.0
           ENC00000005  2017-08-19 09:00:00   92.3
           ENC00000006  2017-09-21 07:00:00   93.1
...                                            ...
PT001200   ENC00028647  2019-07-09 08:00:00    NaN
           ENC00028648  2020-12-28 14:00:00    NaN
           ENC00028649  2021-01-24 09:00:00    NaN
           ENC00028650  2022-04-22 07:00:00    NaN
           ENC00028652  2023-10-20 09:00:00   84.5

[15709 rows x 14 columns]

In [6]:
pivot_icd =pd.pivot_table(df_diagnosis_data, values= 'icd10_code', index= ['patient_id', 'encounter_id', 'diagnosis_date'], columns= 'diagnosis_description', 
                          aggfunc= 'any')
pivot_icd_v2 = (pivot_icd.replace(to_replace=True, value= int(1))).fillna(0)
pivot_icd_v2

diagnosis_description                  Acute myocardial infarction, unspecified  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                            0
                        2015-10-27                                            0
           ENC00000016  2020-08-01                                            0
                        2020-08-27                                            0
                        2020-11-07                                            0
...                                                                         ...
PT001199   ENC00028628  2015-08-17                                            0
                        2015-08-21                                            0
                        2015-08-24                                            0
                        2015-10-23                                            0
                        2015-11-08                                            0

diagnosis_description                  Atherosclerotic heart disease, subclinical  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                              0
                        2015-10-27                                              0
           ENC00000016  2020-08-01                                              0
                        2020-08-27                                              0
                        2020-11-07                                              0
...                                                                           ...
PT001199   ENC00028628  2015-08-17                                              0
                        2015-08-21                                              0
                        2015-08-24                                              0
                        2015-10-23                                              0
                        2015-11-08                                              1

diagnosis_description                  Cerebral infarction, unspecified  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                    0
                        2015-10-27                                    0
           ENC00000016  2020-08-01                                    0
                        2020-08-27                                    0
                        2020-11-07                                    0
...                                                                 ...
PT001199   ENC00028628  2015-08-17                                    0
                        2015-08-21                                    0
                        2015-08-24                                    0
                        2015-10-23                                    0
                        2015-11-08                                    0

diagnosis_description                  Chronic kidney disease, stage 3  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                   0
                        2015-10-27                                   0
           ENC00000016  2020-08-01                                   0
                        2020-08-27                                   0
                        2020-11-07                                   0
...                                                                ...
PT001199   ENC00028628  2015-08-17                                   0
                        2015-08-21                                   1
                        2015-08-24                                   0
                        2015-10-23                                   0
                        2015-11-08                                   0

diagnosis_description                  Chronic kidney disease, stage 4  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                   0
                        2015-10-27                                   0
           ENC00000016  2020-08-01                                   0
                        2020-08-27                                   0
                        2020-11-07                                   0
...                                                                ...
PT001199   ENC00028628  2015-08-17                                   0
                        2015-08-21                                   0
                        2015-08-24                                   0
                        2015-10-23                                   0
                        2015-11-08                                   0

diagnosis_description                  Chronic kidney disease, stage 5  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                   0
                        2015-10-27                                   0
           ENC00000016  2020-08-01                                   0
                        2020-08-27                                   0
                        2020-11-07                                   0
...                                                                ...
PT001199   ENC00028628  2015-08-17                                   0
                        2015-08-21                                   0
                        2015-08-24                                   0
                        2015-10-23                                   0
                        2015-11-08                                   0

diagnosis_description                  Essential (primary) hypertension  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                    0
                        2015-10-27                                    0
           ENC00000016  2020-08-01                                    0
                        2020-08-27                                    1
                        2020-11-07                                    0
...                                                                 ...
PT001199   ENC00028628  2015-08-17                                    0
                        2015-08-21                                    0
                        2015-08-24                                    0
                        2015-10-23                                    0
                        2015-11-08                                    0

diagnosis_description                  Heart failure, unspecified  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                              0
                        2015-10-27                              0
           ENC00000016  2020-08-01                              0
                        2020-08-27                              0
                        2020-11-07                              0
...                                                           ...
PT001199   ENC00028628  2015-08-17                              0
                        2015-08-21                              0
                        2015-08-24                              0
                        2015-10-23                              0
                        2015-11-08                              0

diagnosis_description                  Hyperlipidemia, unspecified  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                               0
                        2015-10-27                               0
           ENC00000016  2020-08-01                               0
                        2020-08-27                               0
                        2020-11-07                               1
...                                                            ...
PT001199   ENC00028628  2015-08-17                               1
                        2015-08-21                               0
                        2015-08-24                               0
                        2015-10-23                               0
                        2015-11-08                               0

diagnosis_description                  Obesity, unspecified  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                        0
                        2015-10-27                        1
           ENC00000016  2020-08-01                        0
                        2020-08-27                        0
                        2020-11-07                        0
...                                                     ...
PT001199   ENC00028628  2015-08-17                        0
                        2015-08-21                        0
                        2015-08-24                        0
                        2015-10-23                        0
                        2015-11-08                        0

diagnosis_description                  Peripheral artery disease, unspecified extremity  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                                    0
                        2015-10-27                                                    0
           ENC00000016  2020-08-01                                                    0
                        2020-08-27                                                    0
                        2020-11-07                                                    0
...                                                                                 ...
PT001199   ENC00028628  2015-08-17                                                    0
                        2015-08-21                                                    0
                        2015-08-24                                                    0
                        2015-10-23                                                    0
                        2015-11-08                                                    0

diagnosis_description                  Prediabetes  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08               1
                        2015-10-27               0
           ENC00000016  2020-08-01               0
                        2020-08-27               0
                        2020-11-07               0
...                                            ...
PT001199   ENC00028628  2015-08-17               0
                        2015-08-21               0
                        2015-08-24               0
                        2015-10-23               0
                        2015-11-08               0

diagnosis_description                  Proteinuria, severely increased  \
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                   0
                        2015-10-27                                   0
           ENC00000016  2020-08-01                                   0
                        2020-08-27                                   0
                        2020-11-07                                   0
...                                                                ...
PT001199   ENC00028628  2015-08-17                                   0
                        2015-08-21                                   0
                        2015-08-24                                   0
                        2015-10-23                                   1
                        2015-11-08                                   0

diagnosis_description                  Type 2 diabetes mellitus without complications
patient_id encounter_id diagnosis_date
PT000001   ENC00000003  2015-03-08                                                  0
                        2015-10-27                                                  0
           ENC00000016  2020-08-01                                                  1
                        2020-08-27                                                  0
                        2020-11-07                                                  0
...                                                                               ...
PT001199   ENC00028628  2015-08-17                                                  0
                        2015-08-21                                                  0
                        2015-08-24                                                  1
                        2015-10-23                                                  0
                        2015-11-08                                                  0

[3736 rows x 14 columns]

Flatten Tables

In [7]:
flat_lab_data = pivot_lab.reset_index(0)
flat_lab_data

,test_name,patient_id,ALT,Fasting Glucose,HDL Cholesterol,HbA1c,Hemoglobin,LDL Cholesterol,Potassium,Serum Albumin,Serum Creatinine,Sodium,Triglycerides,UACR,Uric Acid,eGFR
encounter_id,test_datetime,,,,,,,,,,,,,,,
ENC00000002,2015-07-19 13:00:00,PT000001,NaN,110.0,43.0,NaN,NaN,108.0,NaN,NaN,NaN,NaN,NaN,16.6,NaN,NaN
ENC00000003,2015-10-28 08:00:00,PT000001,NaN,NaN,47.0,6.3,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.6,103.5
ENC00000004,2016-05-29 12:00:00,PT000001,NaN,87.0,NaN,4.9,14.9,115.0,NaN,4.2,NaN,136.0,63.0,26.2,5.0,83.0
ENC00000005,2017-08-19 09:00:00,PT000001,20.0,110.0,70.0,7.9,14.4,NaN,4.4,NaN,0.65,143.0,71.0,6.5,5.0,92.3
ENC00000006,2017-09-21 07:00:00,PT000001,NaN,NaN,38.0,NaN,NaN,104.0,3.9,3.9,0.74,140.0,137.0,15.7,4.9,93.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENC00028647,2019-07-09 08:00:00,PT001200,7.0,78.0,49.0,6.7,11.8,53.0,NaN,3.9,NaN,141.0,136.0,3.4,5.5,NaN
ENC00028648,2020-12-28 14:00:00,PT001200,NaN,64.0,NaN,4.7,15.5,109.0,NaN,4.6,NaN,NaN,109.0,9.7,4.0,NaN
ENC00028649,2021-01-24 09:00:00,PT001200,28.0,128.0,43.0,NaN,15.7,101.0,4.4,NaN,NaN,145.0,NaN,9.0,4.5,NaN
ENC00028650,2022-04-22 07:00:00,PT001200,NaN,109.0,51.0,5.0,NaN,75.0,4.0,4.4,1.00,NaN,NaN,8.5,2.6,NaN
ENC00028652,2023-10-20 09:00:00,PT001200,29.0,102.0,55.0,4.8,12.9,78.0,3.7,3.9,0.75,144.0,111.0,8.0,6.0,84.5

In [8]:
flat_icd = pivot_icd_v2.reset_index()
flat_icd

diagnosis_description,patient_id,encounter_id,diagnosis_date,"Acute myocardial infarction, unspecified","Atherosclerotic heart disease, subclinical","Cerebral infarction, unspecified","Chronic kidney disease, stage 3","Chronic kidney disease, stage 4","Chronic kidney disease, stage 5",Essential (primary) hypertension,"Heart failure, unspecified","Hyperlipidemia, unspecified","Obesity, unspecified","Peripheral artery disease, unspecified extremity",Prediabetes,"Proteinuria, severely increased",Type 2 diabetes mellitus without complications
0,PT000001,ENC00000003,2015-03-08,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,PT000001,ENC00000003,2015-10-27,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,PT000001,ENC00000016,2020-08-01,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,PT000001,ENC00000016,2020-08-27,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,PT000001,ENC00000016,2020-11-07,0,0,0,0,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3731,PT001199,ENC00028628,2015-08-17,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3732,PT001199,ENC00028628,2015-08-21,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3733,PT001199,ENC00028628,2015-08-24,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3734,PT001199,ENC00028628,2015-10-23,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3735,PT001199,ENC00028628,2015-11-08,0,1,0,0,0,0,0,0,0,0,0,0,0,0

Merging Tables

In [9]:
frames = [df_vitals_data, flat_lab_data, flat_icd, df_medications_data, 
          df_history_data, df_procedures_data]

merged_df = pd.merge(df_patient_data, df_enctr_data, on= 'patient_id', 
                     how= 'outer')
for frame in frames:
    merged_df = pd.merge(merged_df, frame, 
                         on= ['patient_id', 'encounter_id'], how= 'outer')

In [ ]:
merged_df.info()

Sorting via .groupby()

In [10]:
merged_df['encounter_datetime'] = pd.to_datetime(merged_df['encounter_datetime'])
data_sorted = merged_df.sort_values(by='encounter_datetime')
data_sorted

,patient_id,sex,year_of_birth,nationality,death_date,encounter_id,encounter_datetime,discharge_datetime,department_specialty,measurement_datetime,...,"Proteinuria, severely increased",Type 2 diabetes mellitus without complications,medication_name,medication_class,dose,dose_unit,smoking_status,alcohol_use,procedure_or_event_code,result_value
32228,PT001099,M,1938,Egypt,NaT,ENC00026249,2015-01-01 07:00:00,2015-01-01 09:00:00,Nephrology,2015-01-01 07:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13836,PT000454,F,1934,India,NaT,ENC00011091,2015-01-01 07:00:00,2015-01-02 07:00:00,Emergency Medicine,2015-01-01 07:00:00,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13837,PT000454,F,1934,India,NaT,ENC00011091,2015-01-01 07:00:00,2015-01-02 07:00:00,Emergency Medicine,2015-01-01 07:00:00,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22496,PT000758,F,1934,United Kingdom,NaT,ENC00018266,2015-01-01 10:00:00,2015-01-01 10:00:00,Endocrinology,2015-01-01 10:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15329,PT000502,F,1983,Philippines,NaT,ENC00012293,2015-01-01 10:00:00,2015-01-01 10:00:00,Endocrinology,NaT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8578,PT000285,F,1964,India,NaT,ENC00006887,2025-12-31 18:00:00,2025-12-31 18:00:00,Internal Medicine,2025-12-31 18:00:00,...,0,1,Lisinopril,ACE Inhibitor,5.0,mg,Never,Occasional,NaN,NaN
8579,PT000285,F,1964,India,NaT,ENC00006887,2025-12-31 18:00:00,2025-12-31 18:00:00,Internal Medicine,2025-12-31 18:00:00,...,0,1,Atorvastatin,Statin,20.0,mg,Never,Occasional,NaN,NaN
8580,PT000285,F,1964,India,NaT,ENC00006887,2025-12-31 18:00:00,2025-12-31 18:00:00,Internal Medicine,2025-12-31 18:00:00,...,0,0,Insulin Glargine,Insulin,5.0,mg,Never,Occasional,NaN,NaN
8581,PT000285,F,1964,India,NaT,ENC00006887,2025-12-31 18:00:00,2025-12-31 18:00:00,Internal Medicine,2025-12-31 18:00:00,...,0,0,Lisinopril,ACE Inhibitor,5.0,mg,Never,Occasional,NaN,NaN
8574,PT000285,F,1964,India,NaT,ENC00006887,2025-12-31 18:00:00,2025-12-31 18:00:00,Internal Medicine,2025-12-31 18:00:00,...,0,0,Insulin Glargine,Insulin,5.0,mg,Never,Occasional,NaN,NaN

In [ ]:
data_sorted.columns

In [11]:
grouped_data = data_sorted.groupby('patient_id').agg(
    encounter_date=('encounter_datetime', 'last'),
    discharge_date = ('discharge_datetime', 'last'),
    dob = ('year_of_birth', 'last'),
    death_date = ('death_date', 'last'),
    sex=('sex', 'first'),
    nationality=('nationality', 'first'),
    height = ('height_value', 'last'),
    weight = ('weight_value', 'last'),
    waist=('waist_circumference_value', 'last'),
    egfr = ('eGFR', 'max'),
    uacr=('UACR', 'max'),
    alt = ('ALT', 'last'),
    fasting_glucose=('Fasting Glucose', 'last'),
    hba1c=('HbA1c', 'last'),
    hemoglobin = ('Hemoglobin', 'last'),
    bmi=('bmi_value', 'last'),
    hdl= ('HDL Cholesterol', 'last'),
    ldl=('LDL Cholesterol', 'last'), 
    sbp=('systolic_bp', 'last'),
    dbp=('diastolic_bp', 'last'),
    triglycerides = ('Triglycerides', 'last'),
    smoking = ('smoking_status', 'max'),
    alcohol = ('alcohol_use', 'max'),
    cardiac_event = ('procedure_or_event_code', 'max'),
    result_cardiac_event = ('result_value', 'max'),
    acute_mi = ('Acute myocardial infarction, unspecified', 'max'),
    subclinical_atherosclerotic_hd = ('Atherosclerotic heart disease, subclinical', 'max'),
    cerebral_infarction = ('Cerebral infarction, unspecified', 'max'),
    ckd_stage3 = ('Chronic kidney disease, stage 3', 'max'),
    ckd_stage4 = ('Chronic kidney disease, stage 4', 'max'),
    ckd_stage5 = ('Chronic kidney disease, stage 5', 'max'),
    htn = ('Essential (primary) hypertension', 'max'),
    hf = ('Heart failure, unspecified', 'max'),
    hyperlipidemia = ('Hyperlipidemia, unspecified', 'max'),
    obesity = ('Obesity, unspecified', 'max'),
    pad = ('Peripheral artery disease, unspecified extremity', 'max'),
    prediabetes = ('Prediabetes', 'max'),
    proteinuria = ('Proteinuria, severely increased', 'max'),
    t2dm = ('Type 2 diabetes mellitus without complications', 'max')
)
grouped_data

,encounter_date,discharge_date,dob,death_date,sex,nationality,height,weight,waist,egfr,...,ckd_stage4,ckd_stage5,htn,hf,hyperlipidemia,obesity,pad,prediabetes,proteinuria,t2dm
patient_id,,,,,,,,,,,,,,,,,,,,,
PT000001,2025-12-15 07:00:00,2025-12-15 10:00:00,1946,NaT,M,Pakistan,183.3,103.0,94.4,103.5,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
PT000002,2025-12-13 08:00:00,2025-12-13 08:00:00,1947,NaT,M,Bangladesh,164.6,93.9,88.2,90.1,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
PT000003,2025-08-29 17:00:00,2025-08-29 17:00:00,1978,NaT,M,Philippines,172.7,70.6,90.2,100.0,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
PT000004,2025-11-02 15:00:00,2025-11-05 15:00:00,1960,NaT,F,India,160.5,86.8,88.5,97.5,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
PT000005,2025-08-30 08:00:00,2025-09-04 08:00:00,1939,NaT,F,UAE,158.2,75.4,85.5,97.5,...,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PT001196,2022-09-15 07:00:00,2022-09-15 07:00:00,1979,2022-09-15,M,India,164.8,92.2,88.9,115.3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
PT001197,2025-12-03 10:00:00,2025-12-03 10:00:00,1971,NaT,M,Pakistan,168.4,86.5,88.8,115.3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
PT001198,2025-09-13 13:00:00,2025-09-13 22:00:00,1956,NaT,F,Philippines,153.5,73.2,88.3,112.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PT001199,2018-09-17 17:00:00,2018-09-17 17:00:00,1941,2018-09-17,F,Philippines,154.1,76.3,88.1,46.4,...,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
PT001200,2025-03-05 12:00:00,2025-03-05 12:00:00,1961,NaT,F,India,156.3,58.3,101.1,104.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
encoded_data = grouped_data.copy()

for column in encoded_data.columns:
    if pd.api.types.is_string_dtype(encoded_data[column]):
        values = encoded_data[column].unique()
        print(f"For {column}: \nUnique values are: {values}")

For sex:
Unique values are: <StringArray>
['M', 'F']
Length: 2, dtype: str
For nationality:
Unique values are: <StringArray>
[      'Pakistan',     'Bangladesh',    'Philippines',          'India',
            'UAE',          'Other',          'Egypt', 'United Kingdom',
         'Jordan']
Length: 9, dtype: str
For smoking:
Unique values are: <StringArray>
['Unknown', 'Never', 'Former', 'Current', nan]
Length: 5, dtype: str
For alcohol:
Unique values are: <StringArray>
['Occasional', 'Never', 'Regular', 'Unknown', nan]
Length: 5, dtype: str
For cardiac_event:
Unique values are: <StringArray>
[nan, 'PROC-ECHO', 'PROC-HD', 'PROC-CATH']
Length: 4, dtype: str

Encode Data

In [13]:
encoded_data['sex'] = encoded_data['sex'].map({'M': 1, 'F': 2})
encoded_data['nationality'] = encoded_data['nationality'].map({
    'Pakistan': 1, 'Bangladesh': 2, 'Philippines': 3, 'India': 4, 
    'UAE': 5, 'Egypt': 6, 'UK' : 7, 'Jordan' : 8, 'Other': 0
})
encoded_data['smoking'] = encoded_data['smoking'].map({'Unknown': 999, 
                                                       'Never': 0, 'Former': 1,
                                                       'Current': 2})
encoded_data['alcohol'] = encoded_data['alcohol'].map({'Occasional': 1, 
                                                       'Never': 2, 'Regular': 3,
                                                       'Unknown': 999})
encoded_data['cardiac_event'] = encoded_data['cardiac_event'].map({'PROC_ECHO': 0,
                                                                   'PROC_HD': 1,
                                                                   'PROC-CATH': 2})

In [14]:
encoded_data.to_csv('encoded_ckm_grouped_by_encounter_date.csv', index=False)