In [1]:
import pandas as pd

In [2]:
pre_staging_df = pd.read_csv(r"C:\Users\HP\Desktop\Projects - Data Analysis\RSF\RSF\hot_encoded_ckm_grouped_by_encounter_date.csv")

In [3]:
cont_df = pre_staging_df[['height_value', 'weight_value', 'bmi_value', 
             'waist_circumference_value', 'systolic_bp', 'diastolic_bp', 'ALT', 
             'Fasting Glucose', 'HDL Cholesterol', 'HbA1c', 'Hemoglobin', 
             'LDL Cholesterol', 'Potassium', 'Serum Albumin', 
             'Serum Creatinine', 'Sodium', 'Triglycerides', 'UACR', 
             'Uric Acid', 'eGFR']]

In [4]:
cont_df

,height_value,weight_value,bmi_value,waist_circumference_value,systolic_bp,diastolic_bp,ALT,Fasting Glucose,HDL Cholesterol,HbA1c,Hemoglobin,LDL Cholesterol,Potassium,Serum Albumin,Serum Creatinine,Sodium,Triglycerides,UACR,Uric Acid,eGFR
0,169.7,93.6,32.5,90.2,118.0,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,189.7,73.1,20.3,85.5,119.0,66.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,165.0,83.9,30.8,86.8,143.0,82.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,161.1,101.8,39.2,84.2,164.0,81.0,28.0,161.0,53.0,6.5,14.9,129.0,4.5,3.9,1.33,138.0,96.0,11.8,5.4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,171.2,52.8,18.0,76.3,118.0,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1196,172.3,87.4,29.4,73.5,137.0,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1197,152.0,57.1,24.7,77.7,103.0,83.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1198,164.4,81.5,30.2,108.2,143.0,83.0,NaN,NaN,25.0,NaN,NaN,103.0,NaN,NaN,1.89,141.0,NaN,NaN,6.0,NaN
1199,162.3,59.9,22.8,84.6,132.0,77.0,NaN,95.0,NaN,NaN,17.0,71.0,3.9,NaN,NaN,141.0,NaN,NaN,NaN,NaN

Mean Calculations

In [5]:
missing_percent = ((cont_df.isnull().sum() / len(cont_df)) * 100).round(2)

In [6]:
missing_data = cont_df.isnull()
not_missing_data = cont_df[~cont_df.isnull()]

print(f"Means missing in missing data: \n {missing_data.mean()}")
print(f"Means missing in normal data: \n {not_missing_data.mean()}")

Means missing in missing data:
 height_value                 0.099167
weight_value                 0.099167
bmi_value                    0.099167
waist_circumference_value    0.099167
systolic_bp                  0.099167
diastolic_bp                 0.099167
ALT                          0.647500
Fasting Glucose              0.657500
HDL Cholesterol              0.646667
HbA1c                        0.645833
Hemoglobin                   0.655833
LDL Cholesterol              0.645000
Potassium                    0.662500
Serum Albumin                0.655833
Serum Creatinine             0.656667
Sodium                       0.655000
Triglycerides                0.651667
UACR                         0.641667
Uric Acid                    0.658333
eGFR                         0.668333
dtype: float64
Means missing in normal data:
 height_value                 163.981684
weight_value                  70.301295
bmi_value                     26.079278
waist_circumference_value     88.008048
systolic_bp                  122.061055
diastolic_bp                  78.071230
ALT                           26.581560
Fasting Glucose              100.656934
HDL Cholesterol               52.610849
HbA1c                          5.582118
Hemoglobin                    13.992252
LDL Cholesterol               99.021127
Potassium                      4.225185
Serum Albumin                  4.321792
Serum Creatinine               0.879612
Sodium                       140.094203
Triglycerides                118.162679
UACR                          17.725581
Uric Acid                      5.225122
eGFR                          95.858040
dtype: float64

MICE

In [7]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.ensemble import RandomForestRegressor

imp = IterativeImputer(
    estimator= RandomForestRegressor(n_estimators=200,
                                     random_state= 42, n_jobs= -1, )
)
cont_df_imputed = pd.DataFrame(imp.fit_transform(cont_df), 
                         columns= cont_df.columns)

c:\Users\HP\Desktop\Projects - Data Analysis\RSF\venv\Lib\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [8]:
cont_df_imputed.describe()

,height_value,weight_value,bmi_value,waist_circumference_value,systolic_bp,diastolic_bp,ALT,Fasting Glucose,HDL Cholesterol,HbA1c,Hemoglobin,LDL Cholesterol,Potassium,Serum Albumin,Serum Creatinine,Sodium,Triglycerides,UACR,Uric Acid,eGFR
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,164.048580,70.525693,26.145971,88.250839,122.160046,77.714508,25.710596,97.586813,53.519433,5.470793,13.980869,96.457221,4.206238,4.334662,0.828498,140.062492,115.063288,13.224872,5.070547,97.459747
std,9.007932,14.540949,4.644679,10.239023,12.615809,8.285373,7.255727,18.735382,7.013357,0.694646,0.906114,19.785910,0.272406,0.212797,0.211400,1.978791,34.589452,28.784715,0.765905,11.347999
min,137.700000,35.900000,16.000000,56.400000,85.000000,55.000000,5.000000,60.000000,15.000000,4.000000,10.100000,35.000000,2.900000,3.200000,0.400000,130.000000,40.000000,1.100000,2.500000,19.400000
25%,158.000000,60.700000,23.000000,81.700000,114.000000,72.000000,20.920000,86.000000,50.007500,5.032375,13.399500,83.632500,4.025750,4.245375,0.714475,139.000000,89.500000,6.226750,4.567375,91.700000
50%,164.300000,70.700000,26.299500,88.500000,122.625000,77.000000,26.000000,94.860000,54.350000,5.300000,13.915000,96.377500,4.200000,4.338250,0.800000,140.020000,114.000000,9.016250,4.987250,99.317250
75%,170.000000,78.700000,29.000000,94.300000,130.000000,83.000000,29.758750,104.000000,57.526250,5.775125,14.637000,109.000000,4.342500,4.443500,0.880000,141.026250,135.395000,12.495125,5.506500,104.509375
max,198.300000,127.400000,40.800000,124.000000,165.000000,105.000000,61.000000,179.000000,82.000000,8.900000,18.300000,168.000000,5.500000,5.400000,3.530000,149.000000,264.000000,601.700000,8.000000,139.100000

Merging the newly Imputed data with the original columns

In [9]:
cate_df = pre_staging_df.drop(columns = cont_df.columns)
imputed_df = pd.concat([cate_df, cont_df_imputed], axis=1)
imputed_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 56 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   patient_id                                        1200 non-null   str
 1   year_of_birth                                     1200 non-null   int64
 2   death_date                                        1200 non-null   int64
 3   encounter_id                                      1200 non-null   str
 4   encounter_datetime                                1200 non-null   int64
 5   discharge_datetime                                1200 non-null   int64
 6   heart_rate                                        1081 non-null   float64
 7   Acute myocardial infarction, unspecified          1200 non-null   float64
 8   Atherosclerotic heart disease, subclinical        1200 non-null   float64
 9   Cerebral infarction, unspecified                  1200 non-null   float64
 10  Chronic kidney disease, stage 3                   1200 non-null   float64
 11  Chronic kidney disease, stage 4                   1200 non-null   float64
 12  Chronic kidney disease, stage 5                   1200 non-null   float64
 13  Essential (primary) hypertension                  1200 non-null   float64
 14  Heart failure, unspecified                        1200 non-null   float64
 15  Hyperlipidemia, unspecified                       1200 non-null   float64
 16  Obesity, unspecified                              1200 non-null   float64
 17  Peripheral artery disease, unspecified extremity  1200 non-null   float64
 18  Prediabetes                                       1200 non-null   float64
 19  Proteinuria, severely increased                   1200 non-null   float64
 20  Type 2 diabetes mellitus without complications    1200 non-null   float64
 21  smoking_status_Former                             1200 non-null   float64
 22  smoking_status_Never                              1200 non-null   float64
 23  smoking_status_Unknown                            1200 non-null   float64
 24  alcohol_use_Occasional                            1200 non-null   float64
 25  alcohol_use_Regular                               1200 non-null   float64
 26  alcohol_use_Unknown                               1200 non-null   float64
 27  sex_M                                             1200 non-null   int64
 28  nationality_Egypt                                 1200 non-null   int64
 29  nationality_India                                 1200 non-null   int64
 30  nationality_Jordan                                1200 non-null   int64
 31  nationality_Other                                 1200 non-null   int64
 32  nationality_Pakistan                              1200 non-null   int64
 33  nationality_Philippines                           1200 non-null   int64
 34  nationality_UAE                                   1200 non-null   int64
 35  nationality_United Kingdom                        1200 non-null   int64
 36  height_value                                      1200 non-null   float64
 37  weight_value                                      1200 non-null   float64
 38  bmi_value                                         1200 non-null   float64
 39  waist_circumference_value                         1200 non-null   float64
 40  systolic_bp                                       1200 non-null   float64
 41  diastolic_bp                                      1200 non-null   float64
 42  ALT                                               1200 non-null   float64
 43  Fasting Glucose                                   1200 non-null   float64
 44  HDL Cholesterol                                   1200 non-null   float64
 45  HbA1c                                             1200 non-null   float64
 46  Hemoglobin                                        1200 non-null   float64
 47  LDL Cholesterol                                   1200 non-null   float64
 48  Potassium                                         1200 non-null   float64
 49  Serum Albumin                                     1200 non-null   float64
 50  Serum Creatinine                                  1200 non-null   float64
 51  Sodium                                            1200 non-null   float64
 52  Triglycerides                                     1200 non-null   float64
 53  UACR                                              1200 non-null   float64
 54  Uric Acid                                         1200 non-null   float64
 55  eGFR                                              1200 non-null   float64
dtypes: float64(41), int64(13), str(2)
memory usage: 525.1 KB

In [10]:
imputed_df.to_csv('imputed_ckm_data.csv', index=False)