In [2]:
import pandas as pd
from scipy.stats import shapiro

In [3]:
df = pd.read_csv(r"C:\Users\HP\Desktop\Projects - Data Analysis\RSF\RSF\ckm_staged_ehr_data.csv")
df

,encounter_date,age,sex,nationality,waist,egfr,uacr,fasting_glucose,hba1c,bmi,...,t2dm,htn,ckd,dyslipidemia,hf,ihd,stroke,pad,subclinical,ckm_stage
0,2026-03-03,54,1,1,96.7,123.9,19.2,5.45,6.0,20.8,...,0,0,0,0,0,0,0,0,0,2
1,2025-03-19,46,1,2,91.0,62.0,242.3,6.16,5.6,35.8,...,0,1,1,0,0,1,0,0,0,4
2,2025-12-05,57,1,3,60.5,70.4,11.1,5.71,4.8,27.0,...,0,0,0,0,0,1,0,0,0,4
3,2025-05-02,69,1,4,104.2,58.7,56.2,6.24,5.2,31.9,...,1,0,0,0,0,0,0,0,0,2
4,2025-11-12,44,2,5,91.5,78.4,107.7,6.65,6.5,30.1,...,0,1,0,1,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2023-09-13,62,1,5,NaN,78.8,64.0,3.67,7.0,27.4,...,0,0,1,0,0,0,0,0,0,2
1996,2025-06-08,47,1,5,93.6,69.4,111.0,5.12,7.4,33.4,...,0,0,0,0,0,0,0,0,0,2
1997,2026-05-31,35,2,4,NaN,86.9,64.1,NaN,4.4,30.5,...,0,0,0,0,0,0,0,0,0,2
1998,2026-06-05,45,1,1,100.1,60.6,201.8,8.16,7.6,34.5,...,0,0,0,0,0,0,0,0,0,2
1999,2024-08-26,37,2,5,93.4,61.9,83.6,7.62,6.3,30.6,...,1,0,1,0,0,0,0,0,0,2

In [4]:
biomarker_cols = ['egfr', 'uacr', 'hba1c', 'ldl', 'chol']
for col in biomarker_cols:
    distribution, pvalue = shapiro(x=df[col], nan_policy='omit')
    print(pvalue)

0.694426895349694
1.6857386722383981e-54
9.658024908304421e-08
0.5963048470981517
0.5556958216083776

In [9]:
egfr_desc_stats = df.groupby('ckm_stage')['egfr'].describe().reset_index()
egfr_desc_stats

   ckm_stage   count       mean        std   min     25%    50%     75%    max
0          0    69.0  93.297101  12.028080  62.3  87.400  92.60  101.70  120.7
1          1     7.0  97.228571  16.800864  77.5  86.500  93.30  104.45  127.9
2          2  1405.0  78.229893  15.037043  44.2  67.400  77.90   88.00  132.9
3          3   208.0  62.762981  17.829870  21.5  48.925  62.55   74.80  105.4
4          4   311.0  67.288746  14.559654  22.0  57.700  68.10   76.00  112.6

This shows that the mean egfr drops the lowest in stage 3 ckm staging.
Stage 3 and 4 CKM show average egfr below 60.

In [10]:
uacr_desc_stats = df.groupby('ckm_stage')['uacr'].describe().reset_index()
uacr_desc_stats

,ckm_stage,count,mean,std,min,25%,50%,75%,max
0,0,68.0,16.233824,6.651486,6.3,10.825,15.15,20.725,29.9
1,1,7.0,19.500000,7.295432,10.2,13.900,19.20,26.150,27.0
2,2,1398.0,70.555079,60.728464,2.5,25.625,50.80,96.050,347.0
3,3,207.0,264.874396,255.674054,12.7,74.650,197.30,381.200,1864.9
4,4,311.0,159.748875,162.456829,8.7,51.300,102.20,221.200,1318.1

In [11]:
hba1c_desc_stats = df.groupby('ckm_stage')['hba1c'].describe().reset_index()
hba1c_desc_stats

   ckm_stage   count      mean       std  min   25%  50%   75%   max
0          0    69.0  4.847826  0.603326  4.0  4.20  4.8  5.50   5.7
1          1     7.0  4.685714  0.606709  4.0  4.25  4.6  5.05   5.6
2          2  1403.0  6.085246  1.012470  4.0  5.40  6.1  6.80  10.0
3          3   208.0  6.672596  1.057738  4.0  6.00  6.7  7.30   9.6
4          4   310.0  6.522903  0.984224  4.0  5.90  6.5  7.20   9.2

In [12]:
ldl_desc_stats = df.groupby('ckm_stage')['ldl'].describe().reset_index()
ldl_desc_stats

   ckm_stage   count      mean       std   min     25%    50%     75%   max
0          0    69.0  2.172174  0.391678  0.89  1.9800  2.340  2.4600  2.60
1          1     7.0  1.847143  0.434845  1.27  1.5650  1.910  2.0550  2.51
2          2  1402.0  3.253531  0.709469  0.60  2.7925  3.280  3.7300  5.69
3          3   206.0  3.634369  0.723823  1.46  3.1800  3.655  4.1675  5.46
4          4   310.0  3.460839  0.727858  1.49  2.9125  3.465  3.9150  5.95

In [13]:
chol_desc_stats = df.groupby('ckm_stage')['chol'].describe().reset_index()
chol_desc_stats

   ckm_stage   count      mean       std   min    25%   50%    75%   max
0          0    69.0  4.991159  0.938620  3.23  4.350  4.91  5.550  7.51
1          1     7.0  4.238571  0.910191  2.60  3.905  4.28  4.825  5.33
2          2  1402.0  5.313902  0.911296  2.47  4.680  5.33  5.920  8.18
3          3   207.0  5.583333  0.896008  2.94  5.065  5.57  6.190  8.07
4          4   309.0  5.597670  1.031953  2.56  4.970  5.64  6.290  8.24

ANOVA (Normal Distribution)

In [9]:
from scipy.stats import f_oneway
def quick_anova(df, cat_var, quant_var):
    var_dir = {0:[], 1:[], 2:[], 3:[], 4:[]}
    for i in range(5):
        var_dir[i] = df.loc[(df[cat_var] == i), quant_var].dropna()
    f_statistic, p_value = f_oneway(var_dir[0], var_dir[1], var_dir[2], 
                                    var_dir[3], var_dir[4])
    return p_value

In [10]:
egfr_anova_pvalue = quick_anova(df, 'ckm_stage', 'egfr')
ldl_anova_pvalue = quick_anova(df, 'ckm_stage', 'ldl')
chol_anova_pvalue = quick_anova(df, 'ckm_stage', 'chol')
print(f"ANOVA results: \negfr: {egfr_anova_pvalue} \nldl: {ldl_anova_pvalue}" + 
      f"\nchol: {chol_anova_pvalue}")

ANOVA results:
egfr: 4.117496934595637e-76
ldl: 2.3156582009341536e-54
chol: 2.528283885490715e-11

Kruskal-Wallis (Skewed Distribution)

In [11]:
from scipy.stats import kruskal
def quick_kruskal(df, cat_var, quant_var):
    var_dir = {0:[], 1:[], 2:[], 3:[], 4:[]}
    for i in range(5):
        var_dir[i] = df.loc[df[cat_var] == i, quant_var].dropna()
    result = kruskal(var_dir[0], var_dir[1], var_dir[2], 
                                    var_dir[3], var_dir[4])
    return result

In [12]:
uacr_kruskal_result = quick_kruskal(df, 'ckm_stage', 'uacr')
hba1c_kruskal_result = quick_kruskal(df, 'ckm_stage', 'hba1c')
print(f"Kruskal-Wallis results: \nuacr: {uacr_kruskal_result}" + 
      f"\nhba1c: {hba1c_kruskal_result}")

Kruskal-Wallis results:
uacr: KruskalResult(statistic=np.float64(418.4499116100814), pvalue=np.float64(2.86708446312185e-89))
hba1c: KruskalResult(statistic=np.float64(203.86591202203144), pvalue=np.float64(5.5415866103008286e-43))