    Practicing EHR dataset grouping based on encounter date of patient and CKM staging protocols

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'C:\Users\HP\Desktop\Projects - Data Analysis\RSF\ckm_raw_ehr.csv')
data

,patient_id,encounter_date,age,sex,nationality_group,egfr,serum_creatinine_umol,uacr_mg_g,hba1c_pct,bmi,...,icd_t2dm,icd_hypertension,icd_ckd,icd_dyslipidaemia,icd_obesity,icd_cvd_heart_failure,icd_cvd_ihd,icd_cvd_stroke,icd_cvd_pad,icd_subclinical_cvd
0,PT00001,2022-12-16,54,Male,Arab Expat,93.3,78.5,10.3,5.2,24.7,...,0,0,0,0,0,0,0,0,0,0
1,PT00001,2023-07-24,54,Male,Arab Expat,93.5,72.8,5.8,NaN,15.3,...,1,0,0,0,0,0,0,0,0,0
2,PT00001,2024-03-28,54,Male,Arab Expat,NaN,84.9,NaN,4.7,NaN,...,0,0,0,0,0,0,0,0,0,0
3,PT00001,2024-04-03,54,Male,Arab Expat,72.5,74.2,2.7,6.9,15.8,...,0,0,0,0,0,0,0,0,0,0
4,PT00001,2024-10-09,54,Male,Arab Expat,94.7,NaN,9.4,4.0,15.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7722,PT01999,2021-06-03,45,Male,Arab Expat,82.4,138.1,59.4,7.1,22.0,...,1,0,0,1,0,0,0,0,0,1
7723,PT02000,2019-07-22,37,Female,South Asian,81.0,107.0,15.2,NaN,29.8,...,0,0,1,0,0,1,0,0,0,0
7724,PT02000,2019-12-27,37,Female,South Asian,62.9,105.6,50.8,7.6,31.1,...,0,0,1,0,1,0,0,0,0,0
7725,PT02000,2021-07-05,37,Female,South Asian,54.5,106.5,44.7,NaN,27.4,...,1,1,0,0,0,0,0,1,0,0
7726,PT02000,2021-07-17,37,Female,South Asian,68.0,NaN,31.0,7.1,36.1,...,0,0,0,1,1,0,0,0,0,1

In [3]:
# Sort by date
data['encounter_date'] = pd.to_datetime(data['encounter_date'])
data = data.sort_values(by='encounter_date')
data

,patient_id,encounter_date,age,sex,nationality_group,egfr,serum_creatinine_umol,uacr_mg_g,hba1c_pct,bmi,...,icd_t2dm,icd_hypertension,icd_ckd,icd_dyslipidaemia,icd_obesity,icd_cvd_heart_failure,icd_cvd_ihd,icd_cvd_stroke,icd_cvd_pad,icd_subclinical_cvd
3487,PT00903,2018-01-01,48,Male,South Asian,86.2,98.6,22.9,6.3,26.5,...,0,1,0,0,0,0,0,0,0,0
2319,PT00603,2018-01-03,60,Female,South Asian,55.1,129.8,72.0,7.2,36.2,...,0,0,1,1,1,0,0,1,0,0
4829,PT01252,2018-01-04,59,Female,South Asian,119.3,89.4,18.5,6.8,30.2,...,0,0,0,0,1,0,0,0,0,0
19,PT00005,2018-01-04,44,Female,South Asian,84.6,131.3,99.2,7.6,31.4,...,0,0,1,1,1,0,0,0,1,0
594,PT00151,2018-01-04,51,Female,South Asian,60.8,108.1,82.8,7.0,37.2,...,0,1,1,1,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7047,PT01827,2024-12-26,32,Male,South Asian,83.3,124.9,11.2,NaN,NaN,...,0,1,0,1,1,0,0,0,0,0
3162,PT00819,2024-12-29,49,Male,Arab Expat,39.8,133.1,36.4,4.5,23.2,...,0,0,0,0,0,0,0,0,0,0
7385,PT01915,2024-12-29,22,Female,African,91.5,108.6,54.9,4.5,24.1,...,0,0,0,0,0,0,0,0,0,0
5060,PT01316,2024-12-30,29,Male,South Asian,81.8,106.3,23.9,5.8,32.5,...,1,1,0,1,1,1,0,1,0,0
7138,PT01852,2024-12-31,72,Male,Western,41.7,137.7,93.3,NaN,33.8,...,1,1,0,1,1,0,0,0,0,0

In [4]:
grouped_data = data.groupby('patient_id').agg(
    encounter_date=('encounter_date', 'last'),
    age=('age', 'first'),
    sex=('sex', 'first'),
    nationality=('nationality_group', 'first'),
    egfr=('egfr', 'last'), 
    uacr=('uacr_mg_g', 'max'),
    hba1c=('hba1c_pct', 'last'),
    bmi=('bmi', 'last'),
    ldl=('ldl_mmol', 'last'), 
    chol=('total_chol_mmol', 'last'),
    sbp=('sbp_mmhg', 'last'),
    dbp=('dbp_mmhg', 'last'),
    prediabetes=('icd_prediabetes', 'max'),
    t2dm=('icd_t2dm', 'max'),
    htn=('icd_hypertension', 'max'),
    ckd=('icd_ckd', 'max'),
    dyslipidemia=('icd_dyslipidaemia', 'max'),
    hf=('icd_cvd_heart_failure', 'max'),
    ihd=('icd_cvd_ihd', 'max'),
    stroke=('icd_cvd_stroke', 'max'),
    pad=('icd_cvd_pad', 'max'),
    subclinical=('icd_subclinical_cvd', 'max')
)
grouped_data

,encounter_date,age,sex,nationality,egfr,uacr,hba1c,bmi,ldl,chol,...,prediabetes,t2dm,htn,ckd,dyslipidemia,hf,ihd,stroke,pad,subclinical
patient_id,,,,,,,,,,,,,,,,,,,,,
PT00001,2024-10-09,54,Male,Arab Expat,94.7,10.3,4.0,15.0,1.39,4.96,...,0,1,0,0,0,0,0,0,0,0
PT00002,2022-06-14,46,Male,East Asian,57.6,29.3,6.4,35.3,1.18,4.50,...,0,1,0,1,0,0,0,0,0,0
PT00003,2024-09-09,57,Male,African,83.0,76.9,7.1,26.7,4.74,5.13,...,0,0,1,0,1,1,1,0,1,0
PT00004,2023-09-13,69,Male,Emirati,91.3,94.9,5.8,33.8,2.84,5.00,...,1,1,1,1,1,0,1,1,1,0
PT00005,2021-07-11,44,Female,South Asian,68.6,99.2,7.6,27.7,3.71,4.60,...,1,1,1,1,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PT01996,2022-05-25,62,Male,South Asian,42.9,120.0,8.7,22.8,4.20,3.91,...,1,1,1,1,1,0,1,0,0,0
PT01997,2021-05-26,47,Male,South Asian,95.4,36.6,5.4,28.9,3.23,6.12,...,0,1,1,1,1,0,0,0,0,1
PT01998,2022-09-19,35,Female,Emirati,71.0,118.0,6.9,22.9,3.12,NaN,...,1,1,1,1,0,1,1,0,0,0
PT01999,2021-06-03,45,Male,Arab Expat,82.4,243.1,7.1,22.0,3.97,5.77,...,1,1,1,1,1,0,1,1,1,1
PT02000,2021-07-17,37,Female,South Asian,68.0,50.8,7.1,36.1,3.79,6.56,...,1,1,1,1,1,1,0,1,0,1

In [5]:
def ckm_staging(row):
    kdigo_g5 = row['egfr'] < 15
    kdigo_g4 = 15 <= row['egfr'] <= 29
    kdigo_g3b = 30 <= row['egfr'] <= 44
    kdigo_g3a = 45 <= row['egfr'] <= 59
    kdigo_g2 = 60 <= row['egfr'] <= 89
    kdigo_g1 = row['egfr'] >= 90

    if row['hf'] or row['ihd'] or row['stroke'] or row['pad']:
        return 4
    elif ((kdigo_g5 or kdigo_g4) or (kdigo_g3b and 30 <= row['uacr'] <= 299) or 
        (kdigo_g3a and row['uacr'] >= 300)) or row['uacr'] >= 300 and (
            row['htn'] or row['hba1c'] > 5.7 or 
            row['prediabetes'] or row['dyslipidemia'] or 
            row['ldl'] > 2.6) or row['subclinical']:
        return 3
    elif (
        ((kdigo_g3b and row['uacr'] < 30) or 
        (kdigo_g3a and row['uacr'] <= 299) or
        ((kdigo_g2 or kdigo_g1) and row['uacr'] >= 30)) or
        (row['htn'] or row['hba1c'] > 5.7 or 
         row['dyslipidemia'] or row['ldl'] > 2.6 or 
         row['prediabetes'] or row['t2dm'])
        ):
        return 2
    elif (
        row['bmi'] >= 30 or row['hba1c'] > 5.7 or row['prediabetes']
        ):
        return 1
    else:
        return 0

In [7]:
ckm_stage = grouped_data.apply(ckm_staging, axis=1)
ckm_stage

patient_id
PT00001    2
PT00002    2
PT00003    4
PT00004    4
PT00005    4
          ..
PT01996    4
PT01997    3
PT01998    4
PT01999    4
PT02000    4
Length: 2000, dtype: int64

In [8]:
prepared_ehr_dataset = pd.concat([grouped_data, pd.Series(ckm_stage, name= 'ckm_stage')], axis=1)
prepared_ehr_dataset

,encounter_date,age,sex,nationality,egfr,uacr,hba1c,bmi,ldl,chol,...,t2dm,htn,ckd,dyslipidemia,hf,ihd,stroke,pad,subclinical,ckm_stage
patient_id,,,,,,,,,,,,,,,,,,,,,
PT00001,2024-10-09,54,Male,Arab Expat,94.7,10.3,4.0,15.0,1.39,4.96,...,1,0,0,0,0,0,0,0,0,2
PT00002,2022-06-14,46,Male,East Asian,57.6,29.3,6.4,35.3,1.18,4.50,...,1,0,1,0,0,0,0,0,0,2
PT00003,2024-09-09,57,Male,African,83.0,76.9,7.1,26.7,4.74,5.13,...,0,1,0,1,1,1,0,1,0,4
PT00004,2023-09-13,69,Male,Emirati,91.3,94.9,5.8,33.8,2.84,5.00,...,1,1,1,1,0,1,1,1,0,4
PT00005,2021-07-11,44,Female,South Asian,68.6,99.2,7.6,27.7,3.71,4.60,...,1,1,1,1,1,0,0,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PT01996,2022-05-25,62,Male,South Asian,42.9,120.0,8.7,22.8,4.20,3.91,...,1,1,1,1,0,1,0,0,0,4
PT01997,2021-05-26,47,Male,South Asian,95.4,36.6,5.4,28.9,3.23,6.12,...,1,1,1,1,0,0,0,0,1,3
PT01998,2022-09-19,35,Female,Emirati,71.0,118.0,6.9,22.9,3.12,NaN,...,1,1,1,0,1,1,0,0,0,4
PT01999,2021-06-03,45,Male,Arab Expat,82.4,243.1,7.1,22.0,3.97,5.77,...,1,1,1,1,0,1,1,1,1,4
PT02000,2021-07-17,37,Female,South Asian,68.0,50.8,7.1,36.1,3.79,6.56,...,1,1,1,1,1,0,1,0,1,4

In [9]:
prepared_ehr_dataset.to_csv('ckm_staged_ehr_data.csv', index=False)